name: build-attest-demo

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: write
  attestations: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true 

    - name: checkout private repo
      uses: actions/checkout@v4
      with:
        repository: omer-io/smol-vs-tokio
        ref: ${{ vars.RELEASE_TAG }}
        token: ${{ secrets.PRIV_REPO }}
        path: smol-vs-tokio
        submodules: true

    - name: Build
      run: |
        cd smol-vs-tokio
        cargo build --release

    - name: Run tests
      run: cargo test --release

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: 'smol-vs-tokio/target/release/smol-vs-tokio'

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: smol-vs-tokio
        path: smol-vs-tokio/target/release/smol-vs-tokio

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: smol-vs-tokio/target/release/smol-vs-tokio
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Securely copy binary to GCP machine
      env:
        GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
        GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
        GCP_VM_USER: ${{ secrets.GCP_VM_USER }}
      run: |
        echo "$GCP_SSH_KEY" > gcp_key.pem
        chmod 600 gcp_key.pem

        scp -o StrictHostKeyChecking=no -i gcp_key.pem \
          smol-vs-tokio/target/release/smol-vs-tokio \
          ${GCP_VM_USER}@${GCP_VM_IP}:${BACKEND_PATH}/

        shred -u gcp_key.pem